package com.webdev.server.POJO;
// Generated Dec 1, 2014 3:59:53 PM by Hibernate Tools 4.3.1



/**
 * BookCat generated by hbm2java
 */
public class BookCat  implements java.io.Serializable {


     private Integer id;
     private Integer bookId;
     private Integer catId;

    public BookCat() {
    }

    public BookCat(Integer bookId, Integer catId) {
       this.bookId = bookId;
       this.catId = catId;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Integer getBookId() {
        return this.bookId;
    }
    
    public void setBookId(Integer bookId) {
        this.bookId = bookId;
    }
    public Integer getCatId() {
        return this.catId;
    }
    
    public void setCatId(Integer catId) {
        this.catId = catId;
    }




}


