package com.webdev.server.POJO;
// Generated Dec 1, 2014 3:59:53 PM by Hibernate Tools 4.3.1



/**
 * UserRole generated by hbm2java
 */
public class UserRole  implements java.io.Serializable {


     private Integer urId;
     private Role role;
     private User user;

    public UserRole() {
    }

    public UserRole(Role role, User user) {
       this.role = role;
       this.user = user;
    }
   
    public Integer getUrId() {
        return this.urId;
    }
    
    public void setUrId(Integer urId) {
        this.urId = urId;
    }
    public Role getRole() {
        return this.role;
    }
    
    public void setRole(Role role) {
        this.role = role;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }




}


