package com.webdev.server.POJO;
// Generated Dec 1, 2014 3:59:53 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private Integer userId;
     private String username;
     private String password;
     private String fullname;
     private String email;
     private Date birthday;
     private Date dateRegister;
     private Set rates = new HashSet(0);
     private Set orderses = new HashSet(0);
     private Set userRoles = new HashSet(0);
     private Set comments = new HashSet(0);
     private Set tokens = new HashSet(0);

    public User() {
    }

	
    public User(String username, String password, Date dateRegister) {
        this.username = username;
        this.password = password;
        this.dateRegister = dateRegister;
    }
    public User(String username, String password, String fullname, String email, Date birthday, Date dateRegister, Set rates, Set orderses, Set userRoles, Set comments, Set tokens) {
       this.username = username;
       this.password = password;
       this.fullname = fullname;
       this.email = email;
       this.birthday = birthday;
       this.dateRegister = dateRegister;
       this.rates = rates;
       this.orderses = orderses;
       this.userRoles = userRoles;
       this.comments = comments;
       this.tokens = tokens;
    }
   
    public Integer getUserId() {
        return this.userId;
    }
    
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getFullname() {
        return this.fullname;
    }
    
    public void setFullname(String fullname) {
        this.fullname = fullname;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Date getBirthday() {
        return this.birthday;
    }
    
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }
    public Date getDateRegister() {
        return this.dateRegister;
    }
    
    public void setDateRegister(Date dateRegister) {
        this.dateRegister = dateRegister;
    }
    public Set getRates() {
        return this.rates;
    }
    
    public void setRates(Set rates) {
        this.rates = rates;
    }
    public Set getOrderses() {
        return this.orderses;
    }
    
    public void setOrderses(Set orderses) {
        this.orderses = orderses;
    }
    public Set getUserRoles() {
        return this.userRoles;
    }
    
    public void setUserRoles(Set userRoles) {
        this.userRoles = userRoles;
    }
    public Set getComments() {
        return this.comments;
    }
    
    public void setComments(Set comments) {
        this.comments = comments;
    }
    public Set getTokens() {
        return this.tokens;
    }
    
    public void setTokens(Set tokens) {
        this.tokens = tokens;
    }




}


